### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ndmitchell** [tibbe/ekg-core#18]
The current HEAD works with GHC 8.2. The latest release does not. A new release would help people trying out ekg-core with GHC 8.2.

**Comment by domenkozar** [comment]
@tibbe

**Comment by 23Skidoo** [comment]
Same applies to `ekg-statsd` et al.

**Comment by 23Skidoo** [comment]
@tibbe If you  help, I can offer to co-maintain the `ekg-` suite of packages.

**Comment by 23Skidoo** [comment]
@tibbe If you need help, I can offer to co-maintain the `ekg-` suite of packages.

**Comment by tibbe** [comment]
@23Skidoo that sounds great. What's your Hackage username?

**Comment by tibbe** [comment]
@23Skidoo I've added you as a collaborator on the 4 GitHub repos and on Hackage. Feel free to merge no-brainer pull requests and make releases. Please update the changeling files and git tag releases like I've done in the past. Thanks!

**Comment by 23Skidoo** [comment]
@tibbe Thanks! Will do.

**Comment by 23Skidoo** [comment]
New releases are now out.
