### ISSUE TITLE
GHC 8.2.1 warnings

### ISSUE THREAD

**Issue by 23Skidoo** [tibbe/ekg-core#19]
The `GHC.Stats` module seems to have been refactored in GHC 8.2.1, so we now get a bunch of warnings of the following type when compiling `System.Metrics`:

```
System/Metrics.hs:414:55: warning: [-Wdeprecations]
    In the use of ‘bytesAllocated’ (imported from GHC.Stats):
    Deprecated: "Use RTSStats instead.  This will be removed in GHC 8.4.1"
    |
414 |      [ ("rts.gc.bytes_allocated"          , Counter . Stats.bytesAllocated)
    |                                                       ^^^^^^^^^^^^^^^^^^^^
```

See [this gist](https://gist.github.com/23Skidoo/b3b1c7d3a0e8f140beb28b6b3e46e907) for the full log. Looks like we'll have to write a compatibility shim to support future GHC versions.

**Comment by 23Skidoo** [comment]
So basically `base-4.10` deprecated `GCStats` in favour of `RTSStats`, which was introduced in `base-4.9`.

**Comment by RyanGlScott** [comment]
Yep, this can be a bit of a bear to migrate to. There are examples of this migration in [`accelerate`](https://github.com/AccelerateHS/accelerate/commit/650ef2d9247cf8889b13edb148520a65b6931fa7) and [`criterion`](https://github.com/bos/criterion/commit/7a47f279b6486f593735ecfd157d904c33622336).

**Comment by lucasdicioccio** [comment]
Is anyone taking this issue? By itself changing the RTS metrics seems OK-ish. The hard bit will be to arrange the code to work with old GHCs as well (there already are a few `#ifdef` around this code).

How much backward support do we want for `ekg-core` (I'd ask for `ekg` in general)?

**Comment by 23Skidoo** [comment]
I'm not aware of anyone working on this right now, so you're welcome to.

> How much backward support do we want for `ekg-core` (I'd ask for `ekg` in general)?

Supporting the GHC versions released during the last three years is a good rule of thumb. This means that we can drop 7.6 and 7.8.
