### ISSUE TITLE
publish to Hackage for GHC 9 support?

### ISSUE THREAD

**Issue by peterbecich** [tibbe/ekg-core#47]
Can a new release including https://github.com/tibbe/ekg-core/pull/43 be published to Hackage? Thanks

**Comment by ejconlon** [comment]
@23Skidoo I believe we can simply create a Hackage revision expanding bounds:

ghc-prim < 0.8,
base >= 4.6 && < 4.16,

+1 and I can do so.

**Comment by ejconlon** [comment]
Also, I do not use this library any more in industry, so we may want to consider opening up contributions from industry stakeholders like Freckle or SimSpace.

**Comment by pbrisbin** [comment]
> we may want to consider opening up contributions from industry stakeholders like Freckle or SimSpace.

We (Freckle) would be happy to help maintain this package. We are waiting on this revision/release and re-inclusion in Stackage for our own package get re-included.

Please let me know how I can help here.

**Comment by brandon-leapyear** [comment]
Dupe of #45?

**Comment by andreasabel** [comment]
To get things rolling, I revised the bounds on hackage: https://hackage.haskell.org/package/ekg-core-0.1.1.7/revisions/

**Comment by peterbecich** [comment]
thanks @andreasabel
